### ISSUE TITLE
Q: LOCAL map type for IPv6 / CALIPSO ?

### ISSUE THREAD

**Issue by hubertqc** [netlabel/netlabel_tools#12]
Hello,

I was wondering if it was a kernel limitation that prevented to have a LOCAL map type for CALIPSO/IPv6.

For now, there is a discrepancy between IPv4 and IPv6 traffic on the loopback interface: the IPv4 traffic gets fully labeled (I mean the sockets get the complete SELinux peer context) and the IPv6 traffic gets only a MLS level label.

Thanks,

Hubert.

**Comment by pcmoore** [comment]
Hi Hubert,

Yes, the Linux Kernel only supports the "local" DOI definition for CIPSO/IPv4; there is no "local" DOI support for CALIPSO/IPv6.  There are a few reasons for this, although none of them are inherent blockers, they could all be worked around if needed.  However, the biggest reason for not implementing a CALIPSO "local" DOI definition is the lack of necessity: if you've built a Linux Kernel with a network stack, you have IPv4 support, and since we are only talking about local/loopback traffic there is no reason not to use the existing CIPSO/IPv4 "local" DOI.  Even on networks that don't support IPv4, you should still be able to use IPv4 over loopback without problem.

Hopefully that answers your question, but if not please let me know.

**Comment by hubertqc** [comment]
Hi Paul,

You perfectly answered my question, thanks a lot.

I have an additional one, though, if you allow me to abuse of your time and knowledge.

The traffic originating from and directed to a host-local IPv4 or IPv6 address (eg 10.0.0.1 and fd5c:feed:beef:face::1 configured on interface `eth1`) will flow through the `lo` interface, as I observed on my host with `tcpdump -i lo -n -nn`.

Therefore, `netlabelctl` can be used to configure the `cipso` protocol so that the  CIPSO/IPv4 "local" map type is used for all host-local IPv4 addresses. And thence, you get "real/full" SELinux peer contexts on IPv4 sockets.
For now, the only SELinux peer context on local-to-local IPv6 sockets gets set up by the "fallback" rules configured using the `unlbl` protocol with `netlabelctl`.

Is there a way to achieve the same goal as the IPv4 "real/full SELinux context" with IPv6 without a "local" DOI for `calipso` ?

Thank you very much for your time and help.

**Comment by pcmoore** [comment]
> Hi Paul,
> 
> You perfectly answered my question, thanks a lot.

Great, glad that helped.

> I have an additional one, though, if you allow me to abuse of your time and knowledge.
> 
> The traffic originating from and directed to a host-local IPv4 or IPv6 address (eg 10.0.0.1 and fd5c:feed:beef:face::1 configured on interface `eth1`) will flow through the `lo` interface, as I observed on my host with `tcpdump -i lo -n -nn`.

Yes, even though it may seem odd, traffic sent from, and destined for, the local system will end up going over the loopback device, even if the the IP addresses are not the traditional "localhost" IP addresses.  As you've seen, this holds true for both IPv4 and IPv6.

> Therefore, `netlabelctl` can be used to configure the `cipso` protocol so that the CIPSO/IPv4 "local" map type is used for all host-local IPv4 addresses. And thence, you get "real/full" SELinux peer contexts on IPv4 sockets. For now, the only SELinux peer context on local-to-local IPv6 sockets gets set up by the "fallback" rules configured using the `unlbl` protocol with `netlabelctl`.

As a reminder, mostly for any others who are reading this issue, it is still possible to use traditional MLS CALIPSO over the loopback device with host-local IPv6 addresses.

> Is there a way to achieve the same goal as the IPv4 "real/full SELinux context" with IPv6 without a "local" DOI for `calipso` ?

At the moment, no.  In order to convey the full SELinux label over a CALIPSO connection, and not just the MLS attributes, a kernel change would be required to support a "local" DOI configuration similar to what we do for CIPSO.

**Comment by hubertqc** [comment]
Thank you very much @pcmoore for all your detailed answers and for your time.
